### ISSUE TITLE
Updated pairs not added to UFO source

### ISSUE THREAD

**Issue by pauldhunt** [adobe-type-tools/kernalytics-rf-ext#8]
I am currently running RoboFont Version 3.2b (built 1809261511) on macOS Mojave version 10.14
Using the Kern-A-Lytics extension does not update UFO masters with kerning from extension.

**Comment by frankrolf** [comment]
Hi Paul, thank you for sharing your UFO files with me. I run Robofont Version 3.2b (built 1809050949) also on Mojave – Kern-A-Lytics seems to work as expected here. I’d update my RF beta, but I am currently on mobile data only.

Here’s the steps to make it work (on my machine):
- open the UFO2 files you provided with RF3
- save the UFO2 files as UFO3 (cmd-s). This will change the structure of the kerning object internally.
- open Kern-A-Lytics and harmonize away. After saving, the applied changes all show for me in a `git log`.

Either something fundamentally changed in the latest Beta, or there is another uncaught issue.
Please try again, I will test the latest Beta as soon as I can.

**Comment by frankrolf** [comment]
I can confirm the above still works with Robofont Version 3.2b (built 1811081816) – the latest beta.
Please let me know if you could make it work, there may be something wrong with that particular Beta you’re running.

**Comment by frankrolf** [comment]
This may have happened when opening a UFO2 file in RF3, and not saving it as UFO3 first.
Closing because I can’t reproduce in normal UFO3 operation.
