### ISSUE TITLE
add extension to Mechanic?

### ISSUE THREAD

**Issue by gferreira** [adobe-type-tools/kernalytics-rf-ext#9]
this is a very nice extension… great example of `Canvas`!

can we add Kern-A-Lytics to [Mechanic](http://robofontmechanic.com/)?

thanks

**Comment by frankrolf** [comment]
Sure! What do you need me to do?

**Comment by gferreira** [comment]
can you please check if the [extension metadata](https://github.com/robofont-mechanic/mechanic-2-server/pull/19/commits/f960ab7058d105348ec638b29d4a9d8e517430df) is correct? thanks!
